"""Initial migration1.

Revision ID: 701058976057
Revises: 
Create Date: 2020-07-01 19:54:28.948221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701058976057'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('ids', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=255), nullable=True),
    sa.Column('lname', sa.String(length=255), nullable=True),
    sa.Column('photos', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ids'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
